version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AudioWorklet
  - Collidoscope
  - Granular
  - Zustand
  - opencollidoscope
  - PGranular
  - ScriptProcessorNode
  - Tonejs
ignoreWords: []
import: []
